<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>IpPreset.Core</RootNamespace>
    <AssemblyName>IpPreset.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
